dist: trusty
sudo: false

language: php

php:
  - '7.1'
  - '7.2'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE printy;'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env.testing

script:
  - vendor/bin/phpunit --coverage-text
